// Package openai provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openai

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ChatCompletionChoiceFinishReason.
const (
	ContentFilter ChatCompletionChoiceFinishReason = "content_filter"
	FunctionCall  ChatCompletionChoiceFinishReason = "function_call"
	Length        ChatCompletionChoiceFinishReason = "length"
	Stop          ChatCompletionChoiceFinishReason = "stop"
	ToolCalls     ChatCompletionChoiceFinishReason = "tool_calls"
)

// Defines values for ChatCompletionRequestMessageRole.
const (
	ChatCompletionRequestMessageRoleAssistant ChatCompletionRequestMessageRole = "assistant"
	ChatCompletionRequestMessageRoleSystem    ChatCompletionRequestMessageRole = "system"
	ChatCompletionRequestMessageRoleUser      ChatCompletionRequestMessageRole = "user"
)

// Defines values for ChatCompletionResponseObject.
const (
	ChatCompletion ChatCompletionResponseObject = "chat.completion"
)

// Defines values for ChatCompletionResponseMessageRole.
const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

// APIError defines model for APIError.
type APIError struct {
	// Code An error code identifying the error type
	Code *string `json:"code"`

	// Message A human-readable error message
	Message string `json:"message"`

	// Param The parameter that caused the error
	Param *string `json:"param"`

	// Type The type of error
	Type string `json:"type"`
}

// ChatCompletionChoice defines model for ChatCompletionChoice.
type ChatCompletionChoice struct {
	// FinishReason The reason the model stopped generating tokens
	FinishReason *ChatCompletionChoiceFinishReason `json:"finish_reason"`

	// Index The index of the choice in the list
	Index   int                           `json:"index"`
	Message ChatCompletionResponseMessage `json:"message"`
}

// ChatCompletionChoiceFinishReason The reason the model stopped generating tokens
type ChatCompletionChoiceFinishReason string

// ChatCompletionRequestMessage defines model for ChatCompletionRequestMessage.
type ChatCompletionRequestMessage struct {
	// Content The contents of the message
	Content string `json:"content"`

	// Name An optional name for the participant
	Name *string `json:"name"`

	// Role The role of the message author
	Role ChatCompletionRequestMessageRole `json:"role"`
}

// ChatCompletionRequestMessageRole The role of the message author
type ChatCompletionRequestMessageRole string

// ChatCompletionResponse defines model for ChatCompletionResponse.
type ChatCompletionResponse struct {
	// Choices A list of chat completion choices
	Choices []ChatCompletionChoice `json:"choices"`

	// Created The Unix timestamp of when the chat completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model The model used for the chat completion
	Model string `json:"model"`

	// Object The object type, which is always "chat.completion"
	Object ChatCompletionResponseObject `json:"object"`

	// SystemFingerprint Fingerprint representing the backend configuration
	SystemFingerprint *string          `json:"system_fingerprint"`
	Usage             *CompletionUsage `json:"usage,omitempty"`
}

// ChatCompletionResponseObject The object type, which is always "chat.completion"
type ChatCompletionResponseObject string

// ChatCompletionResponseMessage defines model for ChatCompletionResponseMessage.
type ChatCompletionResponseMessage struct {
	// Content The contents of the message
	Content *string `json:"content"`

	// Role The role of the author of this message
	Role ChatCompletionResponseMessageRole `json:"role"`
}

// ChatCompletionResponseMessageRole The role of the author of this message
type ChatCompletionResponseMessageRole string

// CompletionUsage defines model for CompletionUsage.
type CompletionUsage struct {
	// CompletionTokens Number of tokens in the generated completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total number of tokens used in the request
	TotalTokens int `json:"total_tokens"`
}

// CreateChatCompletionRequest defines model for CreateChatCompletionRequest.
type CreateChatCompletionRequest struct {
	// FrequencyPenalty Frequency penalty between -2.0 and 2.0
	FrequencyPenalty *float32 `json:"frequency_penalty"`

	// MaxTokens The maximum number of tokens to generate in the chat completion
	MaxTokens *int `json:"max_tokens"`

	// Messages A list of messages comprising the conversation so far
	Messages []ChatCompletionRequestMessage `json:"messages"`

	// Model ID of the model to use (e.g., gpt-4, gpt-3.5-turbo)
	Model string `json:"model"`

	// N How many chat completion choices to generate
	N *int `json:"n"`

	// PresencePenalty Presence penalty between -2.0 and 2.0
	PresencePenalty *float32 `json:"presence_penalty"`

	// Stop Up to 4 sequences where the API will stop generating
	Stop *CreateChatCompletionRequest_Stop `json:"stop"`

	// Temperature Sampling temperature between 0 and 2
	Temperature *float32 `json:"temperature"`

	// TopP Nucleus sampling parameter
	TopP *float32 `json:"top_p"`

	// User A unique identifier representing your end-user
	User *string `json:"user"`
}

// CreateChatCompletionRequestStop0 defines model for .
type CreateChatCompletionRequestStop0 = string

// CreateChatCompletionRequestStop1 defines model for .
type CreateChatCompletionRequestStop1 = []string

// CreateChatCompletionRequest_Stop Up to 4 sequences where the API will stop generating
type CreateChatCompletionRequest_Stop struct {
	union json.RawMessage
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = CreateChatCompletionRequest

// AsCreateChatCompletionRequestStop0 returns the union data inside the CreateChatCompletionRequest_Stop as a CreateChatCompletionRequestStop0
func (t CreateChatCompletionRequest_Stop) AsCreateChatCompletionRequestStop0() (CreateChatCompletionRequestStop0, error) {
	var body CreateChatCompletionRequestStop0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChatCompletionRequestStop0 overwrites any union data inside the CreateChatCompletionRequest_Stop as the provided CreateChatCompletionRequestStop0
func (t *CreateChatCompletionRequest_Stop) FromCreateChatCompletionRequestStop0(v CreateChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChatCompletionRequestStop0 performs a merge with any union data inside the CreateChatCompletionRequest_Stop, using the provided CreateChatCompletionRequestStop0
func (t *CreateChatCompletionRequest_Stop) MergeCreateChatCompletionRequestStop0(v CreateChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateChatCompletionRequestStop1 returns the union data inside the CreateChatCompletionRequest_Stop as a CreateChatCompletionRequestStop1
func (t CreateChatCompletionRequest_Stop) AsCreateChatCompletionRequestStop1() (CreateChatCompletionRequestStop1, error) {
	var body CreateChatCompletionRequestStop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChatCompletionRequestStop1 overwrites any union data inside the CreateChatCompletionRequest_Stop as the provided CreateChatCompletionRequestStop1
func (t *CreateChatCompletionRequest_Stop) FromCreateChatCompletionRequestStop1(v CreateChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChatCompletionRequestStop1 performs a merge with any union data inside the CreateChatCompletionRequest_Stop, using the provided CreateChatCompletionRequestStop1
func (t *CreateChatCompletionRequest_Stop) MergeCreateChatCompletionRequestStop1(v CreateChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateChatCompletionRequest_Stop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateChatCompletionRequest_Stop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
